const dToons = [
    {
        // base toon
        id: 0,
        character: 'Simba',
        color: 'Yellow',
        points: 7,
        kind: 'Lion',
        gender: 'Male',
        role: 'Neutral',
        rarity: 'Rare',
        group: [],
        movie: 'The Lion King',
        abilities: [
            // {
            //     ability: '+3 for each Red or Silver Card in play',
            //     trigger: 'DEFEND',
            //     target: ['color'],
            //     targetCondition: ['Red', 'Silver'],
            //     targetLocation: 'INPLAY',
            //     oneShot: false,
            //     bonus: 3,
            // },
            {
                ability: '+5 to each Red Tribe character in play',
                trigger: 'ATTACK',
                target: ['group', 'color'],
                targetCondition: ['Tribe', 'Red'],
                targetLocation: 'INPLAY',
                oneShot: false,
                bonus: 5,
            },
        ],
        displayImage: 'Here is the DISPLAY image',
        simpleImage: 'Here is the SIMPLE Image',
        gameImage: 'Here is the GAME Image',
    },
    {
        id: 1,
        character: 'Timon',
        color: 'Red',
        points: 3,
        kind: 'Meerekat',
        gender: 'Male',
        role: 'Neutral',
        rarity: 'Rare',
        group: ['Tribe'],
        movie: 'The Lion King',
        abilities: [
            // {
            //     ability: 'no ability',
            //     trigger: 'NONE',
            //     target: null,
            //     targetCondition: [],
            //     targetLocation: null,
            //     oneShot: null,
            //     bonus: null,
            // },
            // {
            //     ability: 'no ability',
            //     trigger: 'NONE',
            //     target: null,
            //     targetCondition: [null],
            //     targetLocation: null,
            //     oneShot: null,
            //     bonus: null,
            // },
        ],
        displayImage: 'Here is the DISPLAY image',
        simpleImage: 'Here is the SIMPLE Image',
        gameImage: 'Here is the GAME Image',
    },
    {
        id: 2,
        character: 'Pumba',
        color: 'Red',
        points: 9,
        kind: 'Warthog',
        gender: 'Male',
        role: 'Neutral',
        rarity: 'Rare',
        group: ['Explorer'],
        movie: 'The Lion King',
        abilities: [
            // {
            //     ability: '+2 for any Timon in play',
            //     trigger: 'DEFEND',
            //     target: 'character',
            //     targetCondition: ['Timon'],
            //     targetLocation: 'INPLAY',
            //     oneShot: true,
            //     bonus: 2,
            // },
            // {
            //     ability: '+1 for any neighboring Rafiki in play',
            //     trigger: 'DEFEND',
            //     target: 'character',
            //     targetCondition: ['Rafiki'],
            //     targetLocation: 'NEIGHBOR',
            //     oneShot: true,
            //     bonus: 1,
            // },
        ],
        displayImage: 'Here is the DISPLAY image',
        simpleImage: 'Here is the SIMPLE Image',
        gameImage: 'Here is the GAME Image',
    },
    {
        id: 3,
        character: 'Rafiki',
        color: 'Silver',
        points: 9,
        kind: 'Monkey',
        gender: 'Male',
        role: 'Neutral',
        rarity: 'Rare',
        group: ['Tribe', 'Explorer'],
        movie: 'The Lion King',
        abilities: [
            // {
            //     ability: 'no ability',
            //     trigger: 'NONE',
            //     target: null,
            //     targetCondition: [null],
            //     targetLocation: null,
            //     oneShot: null,
            //     bonus: null,
            // },
            // {
            //     ability: 'no ability',
            //     trigger: 'NONE',
            //     target: null,
            //     targetCondition: [null],
            //     targetLocation: null,
            //     oneShot: null,
            //     bonus: null,
            // },
        ],
        displayImage: 'Here is the DISPLAY image',
        simpleImage: 'Here is the SIMPLE Image',
        gameImage: 'Here is the GAME Image',
    },
]


module.exports = dToons